import * as P from "./positions";
import type { SceneObject } from "../types";

export const SCENE_OBJECTS: SceneObject[] = [
	{
		path: "models_optimized/weisse_wand_mountain_peek_2517_m_8257_ft_m.glb",
		label: "Mountain Peak",
		position: [0, P.MOUNTAIN_Y, 0],
		scale: P.MOUNTAIN_SCALE,
	},
	{
		path: "models_optimized/pergola.glb",
		label: "Glass Terrace",
		position: [P.PERGOLA_X, P.PERGOLA_Y, P.PERGOLA_Z],
		scale: [P.PERGOLA_SCALE * 0.8, P.PERGOLA_SCALE * 0.5, P.PERGOLA_SCALE * 1.2],
		rotationY: P.PERGOLA_ANGLE,
	},
	{
		path: "models_optimized/jenson_extending_dining_table_solid_oak.glb",
		label: "Desk",
		position: [P.DESK_X, P.DESK_Y, P.DESK_Z],
		scale: [P.DESK_SCALE * 1.8, P.DESK_SCALE * 0.9, P.DESK_SCALE * 1.2],
	},
	{
		path: "models_optimized/harvey_swivel_chair_mineral_blue.glb",
		label: "Chair",
		position: [P.OFFICE_CHAIR_X, P.OFFICE_CHAIR_Y, P.OFFICE_CHAIR_Z],
		scale: P.OFFICE_CHAIR_SCALE,
		rotationY: Math.PI,
	},
	{
		path: "models_optimized/monitor.glb",
		label: "Monitor Left",
		position: [P.MONITOR_A_X, P.MONITOR_A_Y, P.MONITOR_A_Z],
		scale: 1.2,
		rotationY: P.MONITOR_A_ANGLE,
	},
	{
		path: "models_optimized/monitor.glb",
		label: "Monitor Right",
		position: [P.MONITOR_B_X, P.MONITOR_B_Y, P.MONITOR_B_Z],
		scale: 1.2,
		rotationY: P.MONITOR_B_ANGLE,
	},
	{
		path: "models_optimized/monitor.glb",
		label: "Monitor Right",
		position: [P.MONITOR_C_X, P.MONITOR_C_Y, P.MONITOR_C_Z],
		scale: 1.2,
		rotationY: P.MONITOR_C_ANGLE,
	},
	{
		path: "models_optimized/mac_keyboard.glb",
		label: "Keyboard",
		position: [P.KEYBOARD_X, P.KEYBOARD_Y, P.KEYBOARD_Z],
		scale: 0.007,
	},
	{
		path: "models_optimized/mousepad.glb",
		label: "pad",
		position: [P.PAD_X, P.PAD_Y, P.PAD_Z],
		scale: [P.PAD_SCALE * 0.9, P.PAD_SCALE, P.PAD_SCALE * 1.2],
		rotationY: P.PAD_ANGLE,
	},
	{
		path: "models_optimized/lowpoly_laptop_closed.glb",
		label: "Laptop",
		position: [P.LAPTOP_X, P.LAPTOP_Y, P.LAPTOP_Z],
		scale: 1.8,
	},
	{
		path: "models_optimized/the_serpent_-_tret030.glb",
		label: "DESK_LAMP",
		position: [P.DESK_LAMP_X, P.DESK_LAMP_Y, P.DESK_LAMP_Z],
		scale: P.DESK_LAMP_SCALE,
		rotationY: P.DESK_LAMP_ANGLE,
	},
	{
		path: "models_optimized/imac_magic_mouse.glb",
		label: "mouse",
		position: [P.MOUSE_X, P.MOUSE_Y, P.MOUSE_Z],
		scale: 1.5,
	},
	{
		path: "models_optimized/mug.glb",
		label: "Mug",
		position: [P.MUG_X, P.MUG_Y, P.MUG_Z],
		scale: P.MUG_SCALE,
		rotationY: P.MUG_ANGLE,
	},
	{
		path: "models_optimized/unhyun__straw_mat_a.glb",
		label: "COASTER",
		position: [P.COASTER_X, P.COASTER_Y, P.COASTER_Z],
		scale: P.COASTER_SCALE,
		rotationY: P.COASTER_ANGLE,
	},
	{
		path: "models_optimized/rug.glb",
		label: "rug office",
		position: [P.RUG_OFFICE_X, P.RUG_OFFICE_Y, P.RUG_OFFICE_Z],
		scale: [P.RUG_OFFICE_SCALE * 1.85, P.RUG_OFFICE_SCALE, P.RUG_OFFICE_SCALE * 2.5],
		rotationY: P.RUG_OFFICE_ANGLE,
	},
	{
		path: "models_optimized/welcome_text.glb",
		label: "TV_CODE",
		position: [P.TV_CODE_X, P.TV_CODE_Y, P.TV_CODE_Z],
		scale: P.TV_CODE_SCALE,
		rotationY: P.TV_CODE_ANGLE,
	},
	{
		path: "models_optimized/tv_with_a_wall_mount.glb",
		label: "TV",
		position: [P.TV_X, P.TV_Y, P.TV_Z],
		scale: P.TV_SCALE,
		rotationY: P.TV_ANGLE,
	},
	{
		path: "models_optimized/ipad_air4.glb",
		label: "tablet",
		position: [P.TABLET_X, P.TABLET_Y, P.TABLET_Z],
		scale: P.TABLET_SCALE,
		rotationY: P.TABLET_ANGLE,
	},
	{
		path: "models_optimized/bush_square.glb",
		label: "square",
		position: [P.PLANT_SQUARE_X, P.PLANT_SQUARE_Y, P.PLANT_SQUARE_Z],
		scale: [P.PLANT_SQUARE_SCALE * 1.5, P.PLANT_SQUARE_SCALE * 3, P.PLANT_SQUARE_SCALE * 3.5],
		rotationY: P.PLANT_SQUARE_ANGLE,
	},
	{
		path: "models_optimized/bush_square.glb",
		label: "square",
		position: [P.PLANT_SQUARE_B_X, P.PLANT_SQUARE_Y, P.PLANT_SQUARE_B_Z],
		scale: [P.PLANT_SQUARE_SCALE * 1.5, P.PLANT_SQUARE_SCALE * 3, P.PLANT_SQUARE_SCALE * 3.5],
		rotationY: P.PLANT_SQUARE_B_ANGLE,
	},
	{
		path: "models_optimized/bush_square.glb",
		label: "square",
		position: [P.PLANT_SQUARE_C_X, P.PLANT_SQUARE_Y, P.PLANT_SQUARE_C_Z],
		scale: [P.PLANT_SQUARE_SCALE * 1.5, P.PLANT_SQUARE_SCALE * 3, P.PLANT_SQUARE_SCALE * 5],
		rotationY: P.PLANT_SQUARE_C_ANGLE,
	},
	{
		path: "models_optimized/green_creeper_plant.glb",
		label: "creeper",
		position: [P.PLANT_CREEPER_LEFT_X, P.PLANT_CREEPER_LEFT_Y, P.PLANT_CREEPER_LEFT_Z],
		scale: [P.PLANT_CREEPER_LEFT_SCALE * 1.8, P.PLANT_CREEPER_LEFT_SCALE * 1.2, P.PLANT_CREEPER_LEFT_SCALE * 1.2],
		rotationY: P.PLANT_CREEPER_LEFT_ANGLE,
	},
	{
		path: "models_optimized/green_creeper_plant.glb",
		label: "creeper",
		position: [P.PLANT_CREEPER_RIGHT_X, P.PLANT_CREEPER_RIGHT_Y, P.PLANT_CREEPER_RIGHT_Z],
		scale: [P.PLANT_CREEPER_RIGHT_SCALE * 1.3, P.PLANT_CREEPER_RIGHT_SCALE * 1.7, P.PLANT_CREEPER_RIGHT_SCALE * 2],
		rotationY: P.PLANT_CREEPER_RIGHT_ANGLE,
	},
	{
		path: "models_optimized/irvin_floor_lamp_natural_wood_and_white.glb",
		label: "FLOOR_LAMP",
		position: [P.FLOOR_LAMP_X, P.FLOOR_LAMP_Y, P.FLOOR_LAMP_Z],
		scale: P.FLOOR_LAMP_SCALE,
		rotationY: P.FLOOR_LAMP_ANGLE,
	},
	{
		path: "models_optimized/Untitled.glb",
		label: "Armchair",
		position: [P.ARMCHAIR_X, P.ARMCHAIR_Y, P.ARMCHAIR_Z],
		scale: P.ARMCHAIR_SCALE,
		rotationY: P.ARMCHAIR_ANGLE,
	},
	{
		path: "models_optimized/dylan_2_seater_sofa_mineral_blue.glb",
		label: "sofa",
		position: [P.SOFA_X, P.SOFA_Y, P.SOFA_Z],
		scale: [P.SOFA_SCALE * 1.3, P.SOFA_SCALE, P.SOFA_SCALE],
		rotationY: P.SOFA_ANGLE,
	},
	{
		path: "models_optimized/pillow_test.glb",
		label: "pillow",
		position: [P.PILLOW_X, P.PILLOW_Y, P.PILLOW_Z],
		scale: P.PILLOW_SCALE,
		rotationY: P.PILLOW_ANGLE,
	},
	{
		path: "models_optimized/edelweiss_round_table_ash_and_white.glb",
		label: "coffee table",
		position: [P.COFFEE_TABLE_X, P.COFFEE_TABLE_Y, P.COFFEE_TABLE_Z],
		scale: [P.COFFEE_TABLE_SCALE * 1.1, P.COFFEE_TABLE_SCALE * 0.4, P.COFFEE_TABLE_SCALE * 1.3],
	},
	{
		path: "models_optimized/rug.glb",
		label: "rug meeting",
		position: [P.RUG_MEETING_X, P.RUG_MEETING_Y, P.RUG_MEETING_Z],
		scale: [P.RUG_MEETING_SCALE * 1.8, P.RUG_MEETING_SCALE, P.RUG_MEETING_SCALE * 1.6],
	},
	{
		path: "models_optimized/edelweiss_bar_table_ash_and_white.glb",
		label: "bar table",
		position: [P.BAR_TABLE_X, P.BAR_TABLE_Y, P.BAR_TABLE_Z],
		scale: [P.BAR_TABLE_SCALE * 1.2, P.BAR_TABLE_SCALE, P.BAR_TABLE_SCALE * 1.2],
	},
	{
		path: "models_optimized/set_of_2_edelweiss_bar_chairs_white.glb",
		label: "bar chair first",
		position: [P.BAR_CHAIR_FIRST_X, P.BAR_CHAIR_FIRST_Y, P.BAR_CHAIR_FIRST_Z],
		scale: P.BAR_CHAIR_FIRST_SCALE,
		rotationY: P.BAR_CHAIR_FIRST_ANGLE,
	},
	{
		path: "models_optimized/set_of_2_edelweiss_bar_chairs_white.glb",
		label: "bar chair second",
		position: [P.BAR_CHAIR_SECOND_X, P.BAR_CHAIR_SECOND_Y, P.BAR_CHAIR_SECOND_Z],
		scale: P.BAR_CHAIR_SECOND_SCALE,
		rotationY: P.BAR_CHAIR_SECOND_ANGLE,
	},
	{
		path: "models_optimized/shoe_cabinet.glb",
		label: "shelf",
		position: [P.SHELF_X, P.SHELF_Y, P.SHELF_Z],
		scale: [P.SHELF_SCALE * 2.5, P.SHELF_SCALE * 0.7, P.SHELF_SCALE * 1.2],
		rotationY: 0,
	},
	{
		path: "models_optimized/mud_material.glb",
		label: "mud",
		position: [P.MUD_X, P.MUD_Y, P.MUD_Z],
		scale: [P.MUD_SCALE * 3, P.MUD_SCALE, P.MUD_SCALE * 0.5],
	},
	{
		path: "models_optimized/wooden_fence.glb",
		label: "wooden_fence a",
		position: [P.WOODEN_FENCE_A_X, P.WOODEN_FENCE_Y, P.WOODEN_FENCE_Z],
		scale: [P.WOODEN_FENCE_SCALE * 2, P.WOODEN_FENCE_SCALE * 0.6, P.WOODEN_FENCE_SCALE * 6],
		rotationY: P.WOODEN_FENCE_ANGLE,
	},
	{
		path: "models_optimized/wooden_fence.glb",
		label: "wooden_fence a",
		position: [P.WOODEN_FENCE_B_X, P.WOODEN_FENCE_Y, P.WOODEN_FENCE_Z],
		scale: [P.WOODEN_FENCE_SCALE * 2, P.WOODEN_FENCE_SCALE * 0.6, P.WOODEN_FENCE_SCALE * 6],
		rotationY: P.WOODEN_FENCE_ANGLE,
	},
	{
		path: "models_optimized/wooden_fence.glb",
		label: "wooden_fence a",
		position: [P.WOODEN_FENCE_C_X, P.WOODEN_FENCE_Y, P.WOODEN_FENCE_Z],
		scale: [P.WOODEN_FENCE_SCALE * 2, P.WOODEN_FENCE_SCALE * 0.6, P.WOODEN_FENCE_SCALE * 6],
		rotationY: P.WOODEN_FENCE_ANGLE,
	},
	{
		path: "models_optimized/wooden_fence.glb",
		label: "wooden_fence a",
		position: [P.WOODEN_FENCE_D_X, P.WOODEN_FENCE_Y, P.WOODEN_FENCE_Z],
		scale: [P.WOODEN_FENCE_SCALE * 2, P.WOODEN_FENCE_SCALE * 0.6, P.WOODEN_FENCE_SCALE * 6],
		rotationY: P.WOODEN_FENCE_ANGLE,
	},
	{
		path: "models_optimized/wooden_fence.glb",
		label: "wooden_fence a",
		position: [P.WOODEN_FENCE_E_X, P.WOODEN_FENCE_Y, P.WOODEN_FENCE_Z],
		scale: [P.WOODEN_FENCE_SCALE * 2, P.WOODEN_FENCE_SCALE * 0.6, P.WOODEN_FENCE_SCALE * 6],
		rotationY: P.WOODEN_FENCE_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_310.glb",
		label: "jungle geranium",
		position: [P.PLANT_GERANIUM_A_X, P.PLANT_GERANIUM_Y, P.PLANT_GERANIUM_A_Z],
		scale: P.PLANT_GERANIUM_SCALE,
		rotationY: P.PLANT_GERANIUM_A_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_310.glb",
		label: "jungle geranium",
		position: [P.PLANT_GERANIUM_B_X, P.PLANT_GERANIUM_Y, P.PLANT_GERANIUM_B_Z],
		scale: P.PLANT_GERANIUM_SCALE,
		rotationY: P.PLANT_GERANIUM_B_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_310.glb",
		label: "jungle geranium",
		position: [P.PLANT_GERANIUM_C_X, P.PLANT_GERANIUM_Y, P.PLANT_GERANIUM_C_Z],
		scale: P.PLANT_GERANIUM_C_SCALE,
		rotationY: P.PLANT_GERANIUM_C_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_310.glb",
		label: "jungle geranium",
		position: [P.PLANT_GERANIUM_D_X, P.PLANT_GERANIUM_Y, P.PLANT_GERANIUM_D_Z],
		scale: P.PLANT_GERANIUM_SCALE,
		rotationY: P.PLANT_GERANIUM_D_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_310.glb",
		label: "jungle geranium",
		position: [P.PLANT_GERANIUM_E_X, P.PLANT_GERANIUM_Y, P.PLANT_GERANIUM_E_Z],
		scale: P.PLANT_GERANIUM_SCALE,
		rotationY: P.PLANT_GERANIUM_E_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_windmill_palm_1625.glb",
		label: "jungle PALM",
		position: [P.PLANT_PALM_A_X, P.PLANT_PALM_Y, P.PLANT_PALM_A_Z],
		scale: P.PLANT_PALM_A_SCALE,
		rotationY: P.PLANT_PALM_A_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_windmill_palm_1625.glb",
		label: "jungle PALM",
		position: [P.PLANT_PALM_B_X, P.PLANT_PALM_Y, P.PLANT_PALM_B_Z],
		scale: P.PLANT_PALM_B_SCALE,
		rotationY: P.PLANT_PALM_B_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_large-leaved_lupine_318.glb",
		label: "jungle LUPINE",
		position: [P.PLANT_LUPINE_A_X, P.PLANT_LUPINE_Y, P.PLANT_LUPINE_A_Z],
		scale: P.PLANT_LUPINE_A_SCALE,
		rotationY: P.PLANT_LUPINE_A_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_large-leaved_lupine_318.glb",
		label: "jungle LUPINE",
		position: [P.PLANT_LUPINE_B_X, P.PLANT_LUPINE_Y, P.PLANT_LUPINE_B_Z],
		scale: [P.PLANT_LUPINE_B_SCALE * 1.2, P.PLANT_LUPINE_B_SCALE * 0.8, P.PLANT_LUPINE_B_SCALE * 1.2],
		rotationY: P.PLANT_LUPINE_B_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_large-leaved_lupine_318.glb",
		label: "jungle LUPINE",
		position: [P.PLANT_LUPINE_C_X, P.PLANT_LUPINE_Y, P.PLANT_LUPINE_C_Z],
		scale: [P.PLANT_LUPINE_C_SCALE * 1.2, P.PLANT_LUPINE_C_SCALE * 0.8, P.PLANT_LUPINE_C_SCALE * 1.2],
		rotationY: P.PLANT_LUPINE_C_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_large-leaved_lupine_318.glb",
		label: "jungle LUPINE",
		position: [P.PLANT_LUPINE_D_X, P.PLANT_LUPINE_Y, P.PLANT_LUPINE_D_Z],
		scale: [P.PLANT_LUPINE_D_SCALE * 1.2, P.PLANT_LUPINE_D_SCALE * 0.8, P.PLANT_LUPINE_D_SCALE * 1.2],
		rotationY: P.PLANT_LUPINE_D_ANGLE,
	},
	{
		path: "models_optimized/dwarf_snowflake_mock_orange_flowers_spring.glb",
		label: "jungle SNOWFLAKE",
		position: [P.PLANT_SNOWFLAKE_A_X, P.PLANT_SNOWFLAKE_Y, P.PLANT_SNOWFLAKE_A_Z],
		scale: [P.PLANT_SNOWFLAKE_A_SCALE * 1.4, P.PLANT_SNOWFLAKE_A_SCALE * 0.9, P.PLANT_SNOWFLAKE_A_SCALE * 1.4],
		rotationY: P.PLANT_SNOWFLAKE_A_ANGLE,
	},
	{
		path: "models_optimized/dwarf_snowflake_mock_orange_flowers_spring.glb",
		label: "jungle SNOWFLAKE",
		position: [P.PLANT_SNOWFLAKE_B_X, P.PLANT_SNOWFLAKE_Y, P.PLANT_SNOWFLAKE_B_Z],
		scale: [P.PLANT_SNOWFLAKE_B_SCALE * 1.4, P.PLANT_SNOWFLAKE_B_SCALE * 0.7, P.PLANT_SNOWFLAKE_B_SCALE * 1.4],
		rotationY: P.PLANT_SNOWFLAKE_B_ANGLE,
	},
	{
		path: "models_optimized/dwarf_snowflake_mock_orange_flowers_spring.glb",
		label: "jungle SNOWFLAKE",
		position: [P.PLANT_SNOWFLAKE_C_X, P.PLANT_SNOWFLAKE_Y, P.PLANT_SNOWFLAKE_C_Z],
		scale: [P.PLANT_SNOWFLAKE_C_SCALE * 1.4, P.PLANT_SNOWFLAKE_C_SCALE * 0.9, P.PLANT_SNOWFLAKE_C_SCALE * 1.4],
		rotationY: P.PLANT_SNOWFLAKE_C_ANGLE,
	},
	{
		path: "models_optimized/dwarf_snowflake_mock_orange_flowers_spring.glb",
		label: "jungle SNOWFLAKE",
		position: [P.PLANT_SNOWFLAKE_D_X, P.PLANT_SNOWFLAKE_Y, P.PLANT_SNOWFLAKE_D_Z],
		scale: [P.PLANT_SNOWFLAKE_D_SCALE * 1.4, P.PLANT_SNOWFLAKE_D_SCALE * 0.9, P.PLANT_SNOWFLAKE_D_SCALE * 1.4],
		rotationY: P.PLANT_SNOWFLAKE_D_ANGLE,
	},
	{
		path: "models_optimized/croton_leaf_plants.glb",
		label: "jungle CROTON",
		position: [P.PLANT_CROTON_A_X, P.PLANT_CROTON_Y, P.PLANT_CROTON_A_Z],
		scale: P.PLANT_CROTON_A_SCALE,
		rotationY: P.PLANT_CROTON_A_ANGLE,
	},
	{
		path: "models_optimized/croton_leaf_plants.glb",
		label: "jungle CROTON",
		position: [P.PLANT_CROTON_B_X, P.PLANT_CROTON_Y, P.PLANT_CROTON_B_Z],
		scale: P.PLANT_CROTON_B_SCALE,
		rotationY: P.PLANT_CROTON_B_ANGLE,
	},
	{
		path: "models_optimized/croton_leaf_plants.glb",
		label: "jungle CROTON",
		position: [P.PLANT_CROTON_C_X, P.PLANT_CROTON_Y, P.PLANT_CROTON_C_Z],
		scale: P.PLANT_CROTON_C_SCALE,
		rotationY: P.PLANT_CROTON_C_ANGLE,
	},
	{
		path: "models_optimized/croton_leaf_plants.glb",
		label: "jungle CROTON",
		position: [P.PLANT_CROTON_D_X, P.PLANT_CROTON_Y, P.PLANT_CROTON_D_Z],
		scale: P.PLANT_CROTON_D_SCALE,
		rotationY: P.PLANT_CROTON_D_ANGLE,
	},
	{
		path: "models_optimized/wisteria_sinensis005.glb",
		label: "jungle SINENSIS",
		position: [P.PLANT_SINENSIS_A_X, P.PLANT_SINENSIS_Y, P.PLANT_SINENSIS_A_Z],
		scale: [P.PLANT_SINENSIS_A_SCALE, P.PLANT_SINENSIS_A_SCALE * 0.8, P.PLANT_SINENSIS_A_SCALE],
		rotationY: P.PLANT_SINENSIS_A_ANGLE,
	},
	{
		path: "models_optimized/wisteria_sinensis005.glb",
		label: "jungle SINENSIS",
		position: [P.PLANT_SINENSIS_B_X, P.PLANT_SINENSIS_Y, P.PLANT_SINENSIS_B_Z],
		scale: [P.PLANT_SINENSIS_B_SCALE, P.PLANT_SINENSIS_B_SCALE * 0.9, P.PLANT_SINENSIS_B_SCALE],
		rotationY: P.PLANT_SINENSIS_B_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_710.glb",
		label: "jungle BUSH",
		position: [P.PLANT_BUSH_A_X, P.PLANT_BUSH_Y, P.PLANT_BUSH_A_Z],
		scale: [P.PLANT_BUSH_A_SCALE * 1.2, P.PLANT_BUSH_A_SCALE, P.PLANT_BUSH_A_SCALE * 1.3],
		rotationY: P.PLANT_BUSH_A_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_710.glb",
		label: "jungle BUSH",
		position: [P.PLANT_BUSH_B_X, P.PLANT_BUSH_Y, P.PLANT_BUSH_B_Z],
		scale: [P.PLANT_BUSH_B_SCALE * 1.1, P.PLANT_BUSH_B_SCALE, P.PLANT_BUSH_B_SCALE * 1.1],
		rotationY: P.PLANT_BUSH_B_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_710.glb",
		label: "jungle BUSH",
		position: [P.PLANT_BUSH_C_X, P.PLANT_BUSH_Y, P.PLANT_BUSH_C_Z],
		scale: [P.PLANT_BUSH_C_SCALE * 1.2, P.PLANT_BUSH_C_SCALE, P.PLANT_BUSH_C_SCALE * 1.3],
		rotationY: P.PLANT_BUSH_C_ANGLE,
	},
	{
		path: "models_optimized/realistic_hd_chinese_jungle_geranium_710.glb",
		label: "jungle BUSH",
		position: [P.PLANT_BUSH_D_X, P.PLANT_BUSH_Y, P.PLANT_BUSH_D_Z],
		scale: [P.PLANT_BUSH_D_SCALE * 1.2, P.PLANT_BUSH_D_SCALE, P.PLANT_BUSH_D_SCALE * 1.3],
		rotationY: P.PLANT_BUSH_D_ANGLE,
	},
	{
		path: "models_optimized/free_pothos_potted_plant_-_money_plant.glb",
		label: "plant_money",
		position: [P.PLANT_MONEY_X, P.PLANT_MONEY_Y, P.PLANT_MONEY_Z],
		scale: P.PLANT_MONEY_SCALE,
	},
	{
		path: "models_optimized/jenson_sideboard_solid_oak.glb",
		label: "bookcase",
		position: [P.BOOKCASE_X, P.BOOKCASE_Y, P.BOOKCASE_Z],
		scale: [P.BOOKCASE_SCALE * 2.4, P.BOOKCASE_SCALE, P.BOOKCASE_SCALE * 1.5],
		rotationY: P.BOOKCASE_ANGLE,
	},
	{
		path: "models_optimized/fruit_basket.glb",
		label: "ORANGE_FLOWERS",
		position: [P.FRUITS_X, P.FRUITS_Y, P.FRUITS_Z],
		scale: P.FRUITS_SCALE,
	},
	{
		path: "models_optimized/teapot.glb",
		label: "ORANGE_FLOWERS",
		position: [P.TEA_X, P.TEA_Y, P.TEA_Z],
		scale: P.TEA_SCALE,
		rotationY: P.TEA_ANGLE,
	},
	{
		path: "models_optimized/nespresso_machine_2.glb",
		label: "ORANGE_FLOWERS",
		position: [P.COFFEE_X, P.COFFEE_Y, P.COFFEE_Z],
		scale: P.COFFEE_SCALE,
	},
];
